# Roda o kafka e o zookepeper
up:
	docker-compose up -d
down:
	docker-compose down -v
	
list-containers:
	docker-compose ps

# Recupa logs dos containers	
zookeper-logs:
	docker-compose logs zookeeper 
kafka-logs:
	docker-compose logs kafka